# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86da098335eb8becc6922aa605120f1795db201b6d60c936238a8a0ce78ae70f083ffc51d054ed338c2a9b3327f476bd18d5d81051ca7f506fc464d2fc28d38f

test:
  secret_key_base: d180e9ebea54671363418c682762e2826ee9a862a8d066428a88188fde32539ac266557c91128c2570fb18eec980e7ee37c250cd9010562e3ff4c10936e17d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
